<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
		<Version>18.1.0</Version>
    <PackageId>Umbraco.Community.Kanban.Contentment</PackageId>
    <Product>Umbraco.Community.Kanban.Contentment</Product>
    <Title>Umbraco.Community.Kanban.Contentment</Title>
    <Description>Contentment Property provider for Umbraco.Community.Kanban</Description>
    <PackageTags>umbraco plugin package umbraco-marketplace kanban board calendar collection listview</PackageTags>
    <RootNamespace>Umbraco.Community.Kanban</RootNamespace>
    <Authors>Your IT Group</Authors>
		<Copyright>Copyright © 2026 - $([System.DateTime]::Now.Year) © $(Company)</Copyright>
    <PackageProjectUrl>https://github.com/YourITGroup/Umbraco.Community.Kanban</PackageProjectUrl>
		<PackageIconUrl>https://raw.githubusercontent.com/YourITGroup/Umbraco.Community.Kanban/master/assets/Kanban_logo.png</PackageIconUrl>
    <RepositoryUrl>https://github.com/YourITGroup/Umbraco.Community.Kanban</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Community.Contentment" />
    <ProjectReference Include="..\Umbraco.Community.Kanban\Umbraco.Community.Kanban.csproj" />
  </ItemGroup>
</Project>
